### ISSUE TITLE
Vote Button Install - expired trial?

### ISSUE THREAD

**Issue by opendave** [technology-studio/vote-button-support#1]
Good Afternoon!

I just installed the trial to see if it would work for what I need, and the install is already expired (5/10/2022).  We only have a 10 user Confluence Cloud, so I believe this macro would be free to us until we add more users -- but I would still like to test it.

Can you assist?
Thanks,
David

**Comment by erik-slovak** [comment]
@opendave Hello!

Licensing is fully controlled by Atlassian. The plugin should be free for up to 10 users so maybe I'd suggest reaching out Atlassian support and checking out [Pricing FAQ](https://marketplace.atlassian.com/apps/1227326/vote-button?hosting=cloud&tab=pricing). If you have any other questions, just let me know and I'll reopen the issue.
